import { supabaseAdmin } from './server';
import { Article, Block, CreateArticleInput, UpdateArticleInput } from '@/types/article';

// Generate a unique ID
export function generateId(): string {
  return `${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

// Create a new article with blocks
export async function createArticle(input: CreateArticleInput): Promise<Article> {
  const { data: article, error: articleError } = await supabaseAdmin
    .from('articles')
    .insert({
      category: input.category,
      title: input.title,
      published: input.published ?? false,
    })
    .select()
    .single();

  if (articleError) throw articleError;
  if (!article) throw new Error('Failed to create article');

  // Insert blocks (id is auto-generated by database)
  const blocksWithIds = input.blocks.map((block, index) => ({
    article_id: article.id,
    type: block.type,
    content: block.content,
    order_num: index,
  }));

  const { data: blocks, error: blocksError } = await supabaseAdmin
    .from('blocks')
    .insert(blocksWithIds)
    .select();

  if (blocksError) throw blocksError;

  return {
    ...article,
    blocks: blocks || [],
  };
}

// Get an article by ID with blocks
export async function getArticle(id: string): Promise<Article | null> {
  const { data: article } = await supabaseAdmin
    .from('articles')
    .select('*')
    .eq('id', id)
    .single();

  if (!article) return null;

  const { data: blocks } = await supabaseAdmin
    .from('blocks')
    .select('*')
    .eq('article_id', id)
    .order('order_num', { ascending: true });

  return {
    ...article,
    blocks: blocks || [],
  };
}

// Get all articles (optional filters)
export async function getArticles(options?: {
  category?: string;
  published?: boolean;
}): Promise<Article[]> {
  let query = supabaseAdmin
    .from('articles')
    .select('*')
    .order('created_at', { ascending: false });

  if (options?.category) {
    query = query.eq('category', options.category);
  }

  if (options?.published !== undefined) {
    query = query.eq('published', options.published);
  }

  const { data: articles } = await query;

  if (!articles) return [];

  // Get blocks for each article
  const articlesWithBlocks = await Promise.all(
    articles.map(async (article) => {
      const { data: blocks } = await supabaseAdmin
        .from('blocks')
        .select('*')
        .eq('article_id', article.id)
        .order('order_num', { ascending: true });

      return {
        ...article,
        blocks: blocks || [],
      };
    })
  );

  return articlesWithBlocks;
}

// Get published articles by category
export async function getArticlesByCategory(category: string): Promise<Article[]> {
  return getArticles({ category, published: true });
}

// Get latest news (for homepage preview)
export async function getLatestNews(limit: number = 3): Promise<Article[]> {
  const { data: articles } = await supabaseAdmin
    .from('articles')
    .select('*')
    .eq('published', true)
    .order('created_at', { ascending: false })
    .limit(limit);

  if (!articles) return [];

  // Get blocks for each article
  const articlesWithBlocks = await Promise.all(
    articles.map(async (article) => {
      const { data: blocks } = await supabaseAdmin
        .from('blocks')
        .select('*')
        .eq('article_id', article.id)
        .order('order_num', { ascending: true });

      return {
        ...article,
        blocks: blocks || [],
      };
    })
  );

  return articlesWithBlocks;
}

// Update an article
export async function updateArticle(input: UpdateArticleInput): Promise<Article | null> {
  const { id, ...updates } = input;

  // Update article fields
  const updateData: any = {};
  if (updates.category !== undefined) updateData.category = updates.category;
  if (updates.title !== undefined) updateData.title = updates.title;
  if (updates.published !== undefined) updateData.published = updates.published;

  if (Object.keys(updateData).length > 0) {
    const { error: updateError } = await supabaseAdmin
      .from('articles')
      .update(updateData)
      .eq('id', id)
      .select();

    if (updateError) throw updateError;
  }

  // If blocks are provided, replace all blocks
  if (updates.blocks) {
    // Delete existing blocks
    await supabaseAdmin
      .from('blocks')
      .delete()
      .eq('article_id', id);

    // Insert new blocks (id is auto-generated by database)
    const blocksWithIds = updates.blocks.map((block, index) => ({
      article_id: id,
      type: block.type,
      content: block.content,
      order_num: index,
    }));

    const { error: blocksError } = await supabaseAdmin
      .from('blocks')
      .insert(blocksWithIds);

    if (blocksError) throw blocksError;
  }

  return getArticle(id);
}

// Delete an article
export async function deleteArticle(id: string): Promise<boolean> {
  // First check if article exists
  const { data: article } = await supabaseAdmin
    .from('articles')
    .select('id')
    .eq('id', id)
    .single();

  if (!article) {
    return false;
  }

  // Delete blocks first (cascade should handle this, but let's be explicit)
  const { error: blocksError } = await supabaseAdmin
    .from('blocks')
    .delete()
    .eq('article_id', id);

  if (blocksError) {
    console.error('Error deleting blocks:', blocksError);
  }

  // Delete article
  const { error } = await supabaseAdmin
    .from('articles')
    .delete()
    .eq('id', id);

  if (error) {
    console.error('Error deleting article:', error);
    throw error;
  }

  return true;
}

// Get all categories
export async function getCategories(): Promise<string[]> {
  const { data } = await supabaseAdmin
    .from('articles')
    .select('category');

  if (!data) return [];

  const categories = new Set(data.map(row => row.category));
  return Array.from(categories);
}
